# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/common/proto/message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esrc/common/proto/message.proto\x12\x11TestTask.Messages\"\x9c\x02\n\x0eWrapperMessage\x12\x36\n\rfast_response\x18\x01 \x01(\x0b\x32\x1f.TestTask.Messages.FastResponse\x12\x36\n\rslow_response\x18\x02 \x01(\x0b\x32\x1f.TestTask.Messages.SlowResponse\x12L\n\x19request_for_fast_response\x18\x03 \x01(\x0b\x32).TestTask.Messages.RequestForFastResponse\x12L\n\x19request_for_slow_response\x18\x04 \x01(\x0b\x32).TestTask.Messages.RequestForSlowResponse\")\n\x0c\x46\x61stResponse\x12\x19\n\x11\x63urrent_date_time\x18\x01 \x02(\t\".\n\x0cSlowResponse\x12\x1e\n\x16\x63onnected_client_count\x18\x01 \x02(\r\"\x18\n\x16RequestForFastResponse\":\n\x16RequestForSlowResponse\x12 \n\x18time_in_seconds_to_sleep\x18\x01 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.common.proto.message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRAPPERMESSAGE._serialized_start=54
  _WRAPPERMESSAGE._serialized_end=338
  _FASTRESPONSE._serialized_start=340
  _FASTRESPONSE._serialized_end=381
  _SLOWRESPONSE._serialized_start=383
  _SLOWRESPONSE._serialized_end=429
  _REQUESTFORFASTRESPONSE._serialized_start=431
  _REQUESTFORFASTRESPONSE._serialized_end=455
  _REQUESTFORSLOWRESPONSE._serialized_start=457
  _REQUESTFORSLOWRESPONSE._serialized_end=515
# @@protoc_insertion_point(module_scope)
